README.md

We have changed our project idea due to difficulties and lack of resources. @platisd

New Project Idea

---

arduino/smartcar/smartcar.ino

This is the code for the assignment basic obstacle avoidance.

Obstacle_Avoidance

---

README.md

We have taken away godot completely and added what we discussed. @platisd

Updated version for new project idea

---

README.md

We took away random positions of the object as part of the extra and added godot.

Extra project idea update

---

LittleDrivers/app/src/main/AndroidManifest.xml
LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
LittleDrivers/app/src/main/res/layout/activity_main.xml
LittleDrivers/app/src/main/res/values/colors.xml
LittleDrivers/app/src/main/res/values/strings.xml
LittleDrivers/build.gradle

Changed orientation to landscape and removed the action bar and title bar

Landscape orientation

---

arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino
arduino/SMCE_ultrasonic_sensor/vehicle_config.json

Improved the obstacle avoidance by instead of moving the car backwards automatically to get out of the range the car now emergency breaks and lets the user move backwards by themself which made it smoother. Additionally the left and right ultrasonic sensors were angled more to the front to avoid the car's corners crashing into obstacles.

Improvements on obstacle avoidance

---

.github/workflows/android.yml
.github/workflows/testing android.yml

This is now the working Android CI.

Working Android CI

---

LittleDrivers/app/src/main/AndroidManifest.xml
LittleDrivers/app/src/main/java/com/example/littledrivers/SplashActivity.java

The main activity was made into landscape again, as the code was not there. The splash screen's orientation was also changed into landscape. Anasha Sarker and Sadhana  Anandan worked on this code. @AnashaSarker2001

Main activity and splash screen landscape orientation

---

LittleDrivers/app/build.gradle
LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
LittleDrivers/app/src/main/res/layout/activity_main.xml
LittleDrivers/settings.gradle

The joystick was not working properly so we deleted it.

Deletion of joystick

---

arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino

Connected arduino sketch with the camera feed
Co-authored-by: gussamanel <gussamanel@student.gu.se>
Co-authored-by: Shahdmetwally <gusmetwsh@student.gu.se>
Co-authored-by: DimitrisPok <guspokdi@student.gu.se>

Camera feed connection

---

LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java

Changed the path name in Android studios from smartcar to LittleDrivers

Renamed the path from smartcar to LittleDrivers In android studios

---

LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino

Made the obstacle avoidance work with the joystick instead of it being entirely dependent on the keyboard.

Fixed obstacle avoidance bug on joystick

---

arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino

Bug Fix: the car no longer becomes unusable when detecting an obstacle from a distance.  #53 
-----------------------------------------------------------------------------------------------------
Added the option to change the speed of the car using the keys u, i, o. The available speeds are 30, 50 and 70.

Bug fix: The car no longer becomes still when detecting an obstacle.

---

LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
LittleDrivers/app/src/main/res/layout/activity_main.xml
LittleDrivers/app/src/main/res/values/strings.xml

Created warning messages that pop up on the application when the car gets too close to an obstacle.

Warning Message

---

README.md

We updated the introduction to make it fit our product better. We added a switch for automated obstacle avoidance and the ability for the players to choose between different themes to play in. We are using espresso to create automated tests as well.

Update and add small features

---

LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
LittleDrivers/app/src/main/res/layout/activity_main.xml

Created a textView for displaying the speed of the car and connected the speed thats being sent from the emulator to the application.

Displaying the speed of the car

---

LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
LittleDrivers/app/src/main/res/layout/activity_main.xml
LittleDrivers/app/src/main/res/values/strings.xml
arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino

I added the distance mqtt publish to the arduino sketch in order to have access to it when we add the mqtt subscription code later on in MainActivity. I also modified the speed publishing that was already on the sketch to improve code quality. This was done by creating a variable with type String to call whenever needed. I also subscribed to the distance code from the arduino sketch and now the distance is displayed on the screen.
Issue #72.

Displaying distance on application

---

LittleDrivers/app/build.gradle
LittleDrivers/app/src/androidTest/java/com/example/littledrivers/MainActivityTest.kt
LittleDrivers/app/src/main/AndroidManifest.xml
LittleDrivers/app/src/main/res/layout/activity_main.xml
LittleDrivers/build.gradle
LittleDrivers/gradle/wrapper/gradle-wrapper.properties

The first automated test was created. This test checks if the main page shows up in the application.

Automated Tests

---

LittleDrivers/app/src/main/res/layout/activity_main.xml

Added a textView next to the displaying speed, to make it more obvious wat we are displaying.

Displaying a text next to the speed

---

LittleDrivers/app/src/main/java/com/example/littledrivers/MainActivity.java
LittleDrivers/app/src/main/res/layout/activity_main.xml
LittleDrivers/app/src/main/res/values/strings.xml
arduino/SMCE_ultrasonic_sensor/SMCE_ultrasonic_sensor.ino

Created a toggle "Safe drive" that can turn obstacle avoidance on and off.

Obstacle avoidance switch

---

arduino/smartcar/smartcar.ino

Modifying the smartcar.ino file to show the accurate speed of the car. Issue #130

Fixing speed bug

---

LittleDrivers/app/build.gradle

Cited the joystick in the build Gradle.#139

Joystick citation

---

LittleDrivers/app/src/main/res/layout/activity_theme3.xml

The current speed on the third theme was fixed by using constraints.

CurrentSpeedConstraint

---

README.md

The README was edited to follow the requirements for submission. The introduction, what, why and how was edited to follow the user's perspective. Setup, get started, features and software architecture titles were added. The features were explained in detail. Setup, get started and software architecture will be written later. #144

Update README - Intro, what, why, how and features

---

LittleDrivers/app/src/main/java/com/example/littledrivers/Theme1Activity.java

Fixed an issue where the beeping sound was not playing when theme 1 was used.

Fixed sound for theme 1

---

LittleDrivers/app/src/main/java/com/example/littledrivers/Theme1Activity.java
LittleDrivers/app/src/main/java/com/example/littledrivers/Theme2Activity.java
LittleDrivers/app/src/main/java/com/example/littledrivers/Theme3Activity.java
LittleDrivers/app/src/main/java/com/example/littledrivers/Theme4Activity.java
arduino/smartcar/smartcar.ino

A second pull request was created for setting the speed of the car to zero in both the activity classes and the smartcar.ino file. In addition to that the smartcar.ino cases were fixed so that, on the SMCE serial, if one presses the key U the speed will increase by 10 and if one presses the key I the speed will decrease by 10. Issue #158

Making car's minimum speed zero
